package com.ant.assessment.simulation.config;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import org.springframework.context.annotation.Configuration;

import javax.annotation.PostConstruct;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;

@Configuration
public class FirebaseConfig {

    @PostConstruct
    public void init() throws IOException {
        String base64 = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYW50LWNhci1yYWNpbmctc3lzdGVtIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMzRiZWYwMDc4YTA4Y2QyOWUwYjZhODI2ODE2NWM2OGQ1MGIzNzBjYSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZ3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2t3Z2dTbEFnRUFBb0lCQVFEVFhvMGl6aHNQSXBzUlxuZTQrMmQyLzM1THUxalBHeHlWY3JHeDlySWppM3E4QXB1dVRoaXB1d3U2K0R5N0JlbEY1OHIzbG40ZzJ3bW42SVxuYXZCNDBNeXROWXgrOWxRWGVDSG8vc1l4VWFiTGdVWmRHWmR2Q2ZpRllGZVoxVG5PYjBlNFJGRmNMS1I3QnNORFxuSkhXUTVvV2NxL1RNM0hpSGpZUUZwYUUrQmhINWZpYXNjK2pBYkd2dDUydkhIajFqVFlqVUpCWHkyMDJXM1VoVlxuZzdZekl3UDNtUUtnSVZ1WjVoblZyUmxsb2s5QnFOWEZ6YjI2aWFHR09kTGlyUGdOR1NCbEFDRDBkSm01alQ2T1xuVW1ONmcyMGlMeXNyRFNxWmQrUG9KVElhMUpoUXptNGhpeUlBSU91TEZIUzd4azM3QTdwdjNzSnNXYUZkMW42WVxuci9VRUN3VXJBZ01CQUFFQ2dnRUFGRGJCSVpoN1h2MnN2Y1hHenlqcDlOZVRtZit5SjVIOU81cWE3UmgzT3gxNlxuUWFObGV5cFJ6RnVPby9pSlUrbzFoUkFVK0xuV0hGTVNFY0xFWDVGOFdYNDdBdk5VeEcvUk1tS1hHcVZYNGJOcFxud3NLTlNHbTRNaTB1QTRDd1NBMDlXeUp4YzNLemdpNTU0d1JzRitEcjJ6bFlyblRSTkFsMUhFTWtRZlc3cDFQY1xuQXdqT0g0SjRHdlR4WXJONVJSTUJHRHp4ZmtZT1UzUnA5U2VsUjNRNjBxMzNkYjFZRlpra2dZRWV5TG9RdlpQZFxuZkdvY21EUVFwUGlxN2tXdkQ4NUt4NlpDajF0Q1czOWp6ZHdydmw2VVNaVWNnNXNmUVJ0eCtpSXd6NmJpL2RLMFxuMXVYRkJLOVVHanFkSmo3ZnpnNHdtdWM1akhFQWJpc21nVmxsUG50U21RS0JnUUQ4cGtJUWNhcDBiSU5XNXVlc1xudnIvTWY1MnY1dEFPM2gxNHUwY3FBM2Z5d1o4S0ZiY2wvRE1Nem9yR1hxYU10eWtNUDBOcngraXpTRk9MU2dRblxub1ZSTThwU04zVFhUazBvbE82Z0g1VlM1aGk4bHVodWZSRWVWNHp1S085bVc2YXlrMWhWeGxlQ2tTU0F3QnMxN1xuYVptZWRuQWY4K25vYXJPR2R0VGVLb3hUY3dLQmdRRFdMQ1hVZEk1NTZIdTgwOExQUnhFMStwOUkycDVqSjlHMFxuZFM5d1dJaXZMMTQ0aEZZK1BKN1pOWXpNRHlObTVlTVBWdmk1dVVFaUo3VWxlT1d6aXlUdXB3eFZuUVdraGVSZFxubGcvUVpreURNMkRORUxuZ20rellRZzFCUmZHNlNEUXBBeU5aQnhXS3hlcm1OMTdreWIybkI0MGd2T2w5RUNkMFxuaHhOSi9rdEphUUtCZ1FDQTJnbzNlTUVHUDVGOGNLY1hZdkZPeW9jUmZ4WDlmeXBvdUpyQ3dxSWFITVdQenlOcFxuTEFhZE1YbDFVakIrODZycnBCZ3VqL1lOK1lVaU5NMkpxSzNsMEpJVENBNjdxUkxYaW1WWUlZM2tVSnNiRXAralxueXA3M3dyeEs4OXMxTEZmd2VYN1dQeW9pbjJqYkZaMFdvL1RFN0lLaXlUTXlaYmpKaXpGbFhTM1VJUUtCZ1FDS1xuL2pPKzRiWGxYLytOMkZCQmZQbXFjbkFWTSt3K3BZVHUvRzVCRnZQOTNWdmtpZDMrbmhEcEhsdTF3czFTNWphcFxucWVQWmhHVEU2Y2doL1lmMU1ZUlNiWThQc013TXJlZzY1RHgzSHl6Z3FPTlZzbGt2YjRJU0J5dmJCSzJRRzNQZVxuZWU3aXhEb3l5YWRjcU9xb3lGU1FwZEh0UVN5MndWa1p3dCs5MFk3Q29RS0JnUUNNZFR5V3g3aVVLV29YaWlqUlxuRmhOR2xWQmRkOHRYdVJTUjJZSmdzKzZkd2l3RDY5eitKTDUwRFhRSWliMWFMcWdwZUo3ZUlkUzVpYlJBaWZDVlxuWC84R0RucHpWRGJQelNaVmcySGVyRFAyWGpRRFZKeUl0Y1BkaThZUXZtWDJPZksrcWhwSmNrVzJETUo5V2JZSFxuVkNZaG9jbW1QV3F5K2dSdjllL2tnRVE4VXc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQGFudC1jYXItcmFjaW5nLXN5c3RlbS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDk3NDE0Njg5NzMxNjE1NzUyOTkiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZic3ZjJTQwYW50LWNhci1yYWNpbmctc3lzdGVtLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==";

        if (base64 == null || base64.isBlank()) {
            throw new IllegalStateException("FIREBASE_CONFIG_BASE64 is not exist");
        }

        byte[] decoded = Base64.getDecoder().decode(base64);

        FirebaseOptions options = FirebaseOptions.builder()
                .setCredentials(GoogleCredentials.fromStream(new ByteArrayInputStream(decoded)))
                .build();

        if (FirebaseApp.getApps().isEmpty()) {
            FirebaseApp.initializeApp(options);
        }
    }
}



